### ISSUE TITLE
Pickle support for Storage will be removed in torch 1.5

### ISSUE THREAD

**Issue by neverix** [szymonmaszke/torchdata#14]
Hi!
This is an awesome package, but I ran into a warning while using the Pickle cacher:
```
***/site-packages/torch/storage.py:34: FutureWarning: pickle support for Storage will be removed in 1.5. Use `torch.save` instead
  warnings.warn("pickle support for Storage will be removed in 1.5. Use `torch.save` instead", FutureWarning)
```
As far as I understand, it can be fixed by creating a new cacher that will use `torch.save` and `torch.load`. I was planning to open this as a PR, but I couldn't figure out how to set up the test environment so this is an issue instead.

**Comment by szymonmaszke** [comment]
Thanks for reporting. It would be great if you could open a PR with new `cacher` (wondering about the name for it though, maybe `Torch`?). But yes, it would be enough to implement three methods, see `torchdata/cachers.py` and documentation.

When it comes to testing environment and testing locally here are the steps I use:
- new conda environment (you could skip this one)
- install [tox](https://anaconda.org/conda-forge/tox)
- run `tox -e test` from project's root

You can place new test in `tests/cachers_tests.py`, project uses `pytest`. If you open a new PR I will guide you if needed.

**Comment by szymonmaszke** [comment]
Closing, as `nightly` now has `torchdata.cachers.Tensor` (same usage as `torchdata.cachers.Pickle`), will be in docs in the next minor version.
