### ISSUE TITLE
Concatenate datasets with different map function

### ISSUE THREAD

**Issue by bearpaw** [szymonmaszke/torchdata#18]
Hi @szymonmaszke , is it possible to concatenate two datasets with different `map` function? I checked the [doc](https://szymonmaszke.github.io/torchdata/packages/torchdata.datasets.html#torchdata.datasets.ChainDataset) but I am not sure. 
Thank you in advance!

**Comment by szymonmaszke** [comment]
Yes, it was implemented from the very beginning. `map`s are specific for a dataset and all of them are run.
