### ISSUE TITLE
AttributeError: 'Subset' object has no attribute 'map'

### ISSUE THREAD

**Issue by the-david-oy** [szymonmaszke/torchdata#21]
Hello! Thanks so much for this wonderful library.

This is my first time using it, and I'm following the README example and StackOverflow post to apply transformations after splitting the data. However, I am getting the above error when I try to run train_dataset.map(train_transform). Does the wrapper still work, or did I make a mistake somewhere?

```
dataset = td.datasets.WrapDataset(torchvision.datasets.ImageFolder('./root'))

total_num = len(dataset)
train_num = int(0.7 * total_num)
val_num = int(0.2 * total_num)
test_num = total_num - train_num - val_num
train_dataset, val_dataset, test_dataset = torch.utils.data.random_split(
    dataset, (train_num, val_num, test_num)
)

train_dataset = train_dataset.map(train_transform)
```

**Comment by szymonmaszke** [comment]
PyTorch's `torch.utils.data.random_split` returns [`torch.utils.data.Subset`](https://pytorch.org/docs/stable/data.html#torch.utils.data.Subset) which is not an instance of `torchdata.Dataset`, hence it has no `map` functionality.

What one could do instead is:

```
dataset = torchvision.datasets.ImageFolder("./root")

total_num = len(dataset)
train_num = int(0.7 * total_num)
val_num = int(0.2 * total_num)
test_num = total_num - train_num - val_num
train_dataset, val_dataset, test_dataset = [
    td.datasets.WrapDataset(dataset)
    for dataset in torch.utils.data.random_split(
        dataset, (train_num, val_num, test_num)
    )
]

train_dataset = train_dataset.map(train_transform)
```

**Comment by liuzzi** [comment]
the docs show a different way of using this - why?  Docs example doesnt work as random_split returns Subset.

I have also not been able to get the mapped torchvision transform example in the docs to work.  simply nothing happens.  I think this needs an update, or is deprecated with new torch versions?
