### ISSUE TITLE
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

### ISSUE THREAD

**Issue by Koushik0901** [szymonmaszke/torchdata#29]
Hi there, I love the repo and wanted to try it out on a project... but when I import torchdata it gives me this error. I installed the latest version of torchdata using `pip install --upgrade torchdata` and yet it throws this error
`TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases`

**Comment by a-skoryk** [comment]
Hey @Koushik0901 
I think your issue duplicates this [one](https://github.com/szymonmaszke/torchdatasets/issues/20). Though I'm not sure about it.

**Comment by Koushik0901** [comment]
Thanks!
