### ISSUE TITLE
support for pytorch 1.3.0

### ISSUE THREAD

**Issue by faroit** [szymonmaszke/torchdata#9]
first, this is a great package! it seems like to bring the only cool part of tensorflow (tf.data) to pytorch. Thanks for the effort.

Is torch 1.3.0 supported in the current release?

**Comment by szymonmaszke** [comment]
Sorry for late reply and thanks for your interest.

Yes, it should be supported out of the box, no major changes were introduced as far as I can tell. If anything is broken due to PyTorch update, hit me up with an issue, thanks.

**Comment by faroit** [comment]
great to know. I would suggest to update the badges on the readme then to make people aware
